-- Stories table seeds here:
insert into stories (id, title) values (1, 'Welcome');
insert into stories (id, title) values (2, 'Perestroika');
insert into stories (id, title) values (3, 'On Moonlight Bay');
insert into stories (id, title) values (4, 'Nuts');
insert into stories (id, title) values (5, 'Sugar Cane Alley (Rue cases nègres)');
insert into stories (id, title) values (6, 'Revenge of the Nerds IV: Nerds in Love');
insert into stories (id, title) values (7, 'Riddick');
insert into stories (id, title) values (8, 'Fresh Horses');
insert into stories (id, title) values (9, 'Gone with the Wind');
insert into stories (id, title) values (10, 'Philomena');
insert into stories (id, title) values (11, 'Attack the Block');
insert into stories (id, title) values (12, 'Meatballs Part II');
insert into stories (id, title) values (13, 'Halloween II');
insert into stories (id, title) values (14, 'New York Lightboard Record');
insert into stories (id, title) values (15, 'They Made Me a Criminal (I Became a Criminal) (They Made Me a Fugitive)');
insert into stories (id, title) values (16, 'Knights');
insert into stories (id, title) values (17, 'Wilde');
insert into stories (id, title) values (18, 'Broken City');
insert into stories (id, title) values (19, 'Hoodwinked Too! Hood vs. Evil');
insert into stories (id, title) values (20, 'Charlie Chan in the Secret Service');
insert into stories (id, title) values (21, 'Demoted');
insert into stories (id, title) values (22, 'Peepli Live');
insert into stories (id, title) values (23, 'Life of Aleksis Kivi, The (Aleksis Kiven elämä)');
insert into stories (id, title) values (24, 'Dust');
insert into stories (id, title) values (25, 'Back Street');
insert into stories (id, title) values (26, 'Tenderness');
insert into stories (id, title) values (27, 'Dark Wind, The');
insert into stories (id, title) values (28, 'Vanilla Sky');
insert into stories (id, title) values (29, 'Believer, The');
insert into stories (id, title) values (30, 'Don''t Look Back (Ne te retourne pas)');
insert into stories (id, title) values (31, 'Perfect Couple, A');
insert into stories (id, title) values (32, 'Sliver');
insert into stories (id, title) values (33, 'House on Haunted Hill');
insert into stories (id, title) values (34, 'Snowball Effect: The Story of ''Clerks''');
insert into stories (id, title) values (35, 'Stevie Nicks: Live at Red Rocks');
insert into stories (id, title) values (36, 'Witless Protection');
insert into stories (id, title) values (37, 'Wedding Crashers');
insert into stories (id, title) values (38, 'Reagan');
insert into stories (id, title) values (39, 'Scotland, Pa.');
insert into stories (id, title) values (40, 'Betty');
insert into stories (id, title) values (41, 'Motorcycle Diaries, The (Diarios de motocicleta)');
insert into stories (id, title) values (42, 'Painted Lady');
insert into stories (id, title) values (43, 'Hank and Mike');
insert into stories (id, title) values (44, 'My Best Friend''s Wedding');
insert into stories (id, title) values (45, 'Hysteria: The Def Leppard Story');
insert into stories (id, title) values (46, 'Visiteurs du soir, Les (Devil''s Envoys, The)');
insert into stories (id, title) values (47, 'Beguiled, The');
insert into stories (id, title) values (48, 'High Hopes');
insert into stories (id, title) values (49, 'Weekend');
insert into stories (id, title) values (50, 'Pride and Prejudice');
