insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (1, 2, 2, 'Until one day there was a massive dust storm! I just had to save EVE. I took her to my shelter where I showed her one of my treasures, a living plant.', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (1, 5, 3, 'Then EVE took the plant, and shutdown! I was so scared... what happened to my EVE?!! But I kept taking care and protecting her for days, until...', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (1, 7, 4, 'Until a big spaceship came and took my EVE away! I could not live without her, so I hung on to that ship for dear robotlife!', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (1, 9, 5, 'The ship had humans in it. And it also had evil robots. The evil robots wanted to destroy EVE and the living plant.', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (1, 8, 6, 'I found EVE and we helped the humans see that the evil robots wanted them to die. With their help we all went back to Earth, cleaned it up and now EVE and I are happy for ever after. The End!', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (1, 9, 1, 'I was lovestruck! I did not know it at the time, but EVE was sent to Earth to find if life existed on Earth. Because of that, she ignored me completely.', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (2, 1, 1, ' Master Luke, his rebel friends and myself had gone to Endor, the home of the Ewoks.', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (2, 4, 2, 'The little furry Ewoks would scare anyone who dare gaze upon them. I, C-3PO, was not scared! And given that I was the only one in our party who could communicate with the furry fellas...', true);
insert into contributions (story_id, user_id, chapter_number, ctext, accepted) values (2, 6, 3, 'I was brought to one of their huts, where proceeded to tell them about the journey we had been on. I told them about the wicked Darth Vader and our struggle against the Empire. Once I finished explaining ...', false);
